repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic]

-   repo: local
    hooks:
    -   id: check-identity
        name: Enforce Author Identity
        entry: |
            bash -c '
            REQUIRED_MAIL="mail@benjamin-foerster.de";
            ACTUAL_MAIL=$(git config user.email);
            SIGNING_ENABLED=$(git config commit.gpgsign);
            
            if [ "$ACTUAL_MAIL" != "$REQUIRED_MAIL" ]; then
              echo "❌ ERROR: Wrong Git Email!";
              echo "Expected: $REQUIRED_MAIL";
              echo "Found:    $ACTUAL_MAIL";
              exit 1;
            fi;

            if [ "$SIGNING_ENABLED" != "true" ]; then
              echo "❌ ERROR: GPG signing is disabled in git config.";
              echo "Run: git config commit.gpgsign true";
              exit 1;
            fi'
        language: system
        pass_filenames: false
        always_run: true