import logging

from app.domain.ports import LLMGenerator

logger = logging.getLogger(__name__)


class DocumentSummarizer:
    """Orchestrator for generating global document summaries.

    Uses a Large Language Model to synthesize a high-level summary from
    the most representative chunks of a document.
    """

    def __init__(self, llm_generator: LLMGenerator):
        """Initialize the summarizer.

        Args:
            llm_generator: The LLM generator to use for summarization.
        """
        self.llm = llm_generator

    def _clean_think_tags(self, text: str) -> str:
        """Removes the <think> blocks generated by DeepSeek-R1 to save tokens."""
        if "</think>" in text:
            return text.split("</think>", 1)[-1].strip()
        return text.strip()

    def _create_super_chunks(self, chunks: list[str], max_tokens: int = 6000) -> list[str]:
        """Combines small retrieval chunks into massive chunks to minimize LLM calls."""
        # Note: A rough heuristic is 1 token ~= 4 characters in English
        max_chars = max_tokens * 4
        super_chunks = []
        current_chunk = ""

        for chunk in chunks:
            if len(current_chunk) + len(chunk) > max_chars:
                super_chunks.append(current_chunk)
                current_chunk = chunk
            else:
                current_chunk += "\n\n" + chunk

        if current_chunk:
            super_chunks.append(current_chunk)

        return super_chunks

    async def generate_global_summary(self, raw_chunks: list[str]) -> str:
        """Executes the CPU-optimized Map-Reduce summarization."""
        super_chunks = self._create_super_chunks(raw_chunks)
        logger.info(
            f"[MAP-REDUCE] Grouped {len(raw_chunks)} chunks into {len(super_chunks)} Super-Chunks."
        )

        map_summaries = []

        # --- PHASE 1: THE MAP ---
        # Execute strictly sequentially to prevent CPU thread locking/OOM
        for i, text in enumerate(super_chunks):
            logger.info(f"[MAP-REDUCE] Mapping Super-Chunk {i + 1}/{len(super_chunks)}...")

            map_prompt = (
                "You are an expert technical analyst. Extract the most critical facts, "
                "entities, and arguments from the following text.\n\n"
                "CRITICAL INSTRUCTION: Output ONLY a strict bulleted list. Be extremely concise.\n\n"
                f"TEXT:\n{text}"
            )

            raw_response = await self.llm.agenerate(prompt=map_prompt)
            clean_response = self._clean_think_tags(raw_response)
            map_summaries.append(clean_response)

        # --- PHASE 2: THE REDUCE ---
        logger.info("[MAP-REDUCE] Executing Final Reduction...")
        combined_bullets = "\n\n".join(map_summaries)

        reduce_prompt = (
            "You are an expert technical writer. I will provide you with bulleted summaries "
            "extracted from a single large document. \n\n"
            "Synthesize these points into a highly professional, cohesive executive summary. "
            "Do not just list the points; weave them into a narrative that explains the "
            "document's overall purpose, methodology, and conclusions.\n\n"
            f"DOCUMENT DATA:\n{combined_bullets}"
        )

        final_raw_response = await self.llm.agenerate(prompt=reduce_prompt)
        final_summary = self._clean_think_tags(final_raw_response)

        logger.info("[MAP-REDUCE] Global Summary Generation Complete.")
        return final_summary
