"""Map-Reduce summarization logic for large-scale document synthesis.

This module implements a scalable summarization architecture designed to process
documents that exceed a single LLM's context window. It utilizes a hierarchical
Map-Reduce pattern, optimized for CPU-bound local environments.
"""

import logging

from app.core.interfaces import LLMGenerator

logger = logging.getLogger(__name__)


class DocumentSummarizer:
    """Hierarchical orchestrator for global document synthesis.

    This class provides the logic to generate a cohesive executive summary of
    an entire document, regardless of its length. It employs a two-stage
    Map-Reduce strategy:

    Pipeline Role:
        Phase 8: Summarization. Hierarchical synthesis of document content
        after vectorization and graph extraction are complete.
    1. **Map Phase**: Fragments of the document are summarized into dense,
       fact-heavy bullet points.
    2. **Reduce Phase**: These bullet points are synthesized into a final,
       professionally formatted narrative.
    Design Considerations:
        - **Token Efficiency**: Groups small chunks into 'super-chunks' to
          minimize expensive LLM context overhead and API calls.
        - **Memory Safety**: Processes map operations sequentially to prevent
          CPU thread-locking and memory spikes in local inference environments.
        - **Model Optimization**: Specifically handles thinking-block removal
          for reasoning models like DeepSeek-R1.
    """

    def __init__(self, llm_generator: LLMGenerator):
        """Initialize the summarizer with an abstraction-aware generator.

        Args:
            llm_generator: A concrete implementation of the LLMGenerator
                interface used for inference.
        """
        self.llm = llm_generator

    def _clean_think_tags(self, text: str) -> str:
        """Removes the <think> blocks generated by DeepSeek-R1 to save tokens.

        Args:
            text: The raw response text from the LLM.

        Returns:
            The text with thinking blocks removed.
        """
        if "</think>" in text:
            return text.split("</think>", 1)[-1].strip()
        return text.strip()

    def _create_super_chunks(self, chunks: list[str], max_tokens: int = 6000) -> list[str]:
        """Combines small retrieval chunks into massive chunks to minimize LLM calls.

        Args:
            chunks: A list of small text fragments.
            max_tokens: The target token limit for each combined chunk.

        Returns:
            A list of larger 'super-chunks'.
        """
        # Note: A rough heuristic is 1 token ~= 4 characters in English
        max_chars = max_tokens * 4
        super_chunks = []
        current_chunk = ""
        for chunk in chunks:
            if len(current_chunk) + len(chunk) > max_chars:
                super_chunks.append(current_chunk)
                current_chunk = chunk
            else:
                current_chunk += "\n\n" + chunk
        if current_chunk:
            super_chunks.append(current_chunk)
        return super_chunks

    async def generate_global_summary(self, raw_chunks: list[str]) -> str:
        """Executes the CPU-optimized Map-Reduce summarization.

        Args:
            raw_chunks: All text chunks extracted from the document.

        Returns:
            A cohesive, professional executive summary of the entire document.
        """
        super_chunks = self._create_super_chunks(raw_chunks)
        logger.info(
            f"[MAP-REDUCE] Grouped {len(raw_chunks)} chunks into {len(super_chunks)} Super-Chunks."
        )
        map_summaries = []
        # --- PHASE 1: THE MAP ---
        # Execute strictly sequentially to prevent CPU thread locking/OOM
        for i, text in enumerate(super_chunks):
            logger.info(f"[MAP-REDUCE] Mapping Super-Chunk {i + 1}/{len(super_chunks)}...")
            map_prompt = (
                "You are an expert technical analyst. Extract the most critical facts, "
                "entities, and arguments from the following text.\n\n"
                "CRITICAL INSTRUCTION: Output ONLY a strict bulleted list. Be extremely concise.\n\n"
                f"TEXT:\n{text}"
            )
            raw_response = await self.llm.agenerate(prompt=map_prompt)
            clean_response = self._clean_think_tags(raw_response)
            map_summaries.append(clean_response)
        # --- PHASE 2: THE REDUCE ---
        logger.info("[MAP-REDUCE] Executing Final Reduction...")
        combined_bullets = "\n\n".join(map_summaries)
        reduce_prompt = (
            "You are an expert technical writer. I will provide you with bulleted summaries "
            "extracted from a single large document. \n\n"
            "Synthesize these points into a highly professional, cohesive executive summary. "
            "Do not just list the points; weave them into a narrative that explains the "
            "document's overall purpose, methodology, and conclusions.\n\n"
            f"DOCUMENT DATA:\n{combined_bullets}"
        )
        final_raw_response = await self.llm.agenerate(prompt=reduce_prompt)
        final_summary = self._clean_think_tags(final_raw_response)
        logger.info("[MAP-REDUCE] Global Summary Generation Complete.")
        return final_summary
